### ISSUE TITLE
Drag works only for first time on mobile (touch) device

### ISSUE THREAD

**Issue by chicko01** [amendx/vue-dndrop#79]
On mobile (or touch) device dragging works only for first time. Then you cannot grab (start dragging).
Issue is reproducible for example on https://amendx.github.io/vue-dndrop/examples/drag-handle.html.

Problem is caused by removing (and not adding back) 'touchstart' event after finishing first drag (mouseUp function).

https://github.com/amendx/vue-dndrop/blob/master/src/utils/container/mediator.js#L405 -> https://github.com/amendx/vue-dndrop/blob/master/src/utils/container/mediator.js#L38

**Comment by marina31714** [comment]
I have the same issue and tablet, have you solved it? Is there any new information?

**Comment by krisdarryn-mrm** [comment]
Hi, Is there any update on this issue? Thank you.

**Comment by EmanuelCostaa** [comment]
I have the same issue. Is there any new information?
Maybe https://www.uriports.com/blog/easy-fix-for-intervention-ignored-attempt-to-cancel-a-touchmove-event-with-cancelable-false/ can have the solution.

**Comment by krisdarryn-mrm** [comment]
> I have the same issue. Is there any new information?
> Maybe https://www.uriports.com/blog/easy-fix-for-intervention-ignored-attempt-to-cancel-a-touchmove-event-with-cancelable-false/ can have the solution.

This one is promising, thank you for sharing.

**Comment by LucasRosas** [comment]
Same issue here. Is there any new information?

1. The function removeGrabListeners () is really necessary?

2. here in my computer I got this error:
![image](https://user-images.githubusercontent.com/8129237/235136411-a2dec626-96b2-46b6-8fbe-a5c903d94606.png)

3. I think the html scroll has to be disabled so as not to be confused with the drag action.

**Comment by LucasRosas** [comment]
I found a solution!! Not the most elegant, but it worked. 😄 
- I replaced the `render` functions with `setup` and had to **import { h } from 'vue'**:
![image](https://user-images.githubusercontent.com/8129237/235367593-a17eb821-cd2b-4de7-a6e4-988e114034ba.png)
![image](https://user-images.githubusercontent.com/8129237/235367568-6f25d854-00b1-4f85-8ddc-67f90c2ab63c.png)

Notice that I passed the `wrapChild` function inside setup(). And since setup takes prop and contect as parameters, I also changed `this.$slots.default` to `context.slots.default()`.

-(I don't know if it's necessary) I added $context.$emits in the props variable of mapOptions
![image](https://user-images.githubusercontent.com/8129237/235367900-151d548d-02c7-433c-a478-35389fcf4176.png)


> ✅  **Ckeck**
> At that point the problem with the touch on the second element had been fixed! But the components stopped emitting events.

- I renamed eventEmitterMap keys
![image](https://user-images.githubusercontent.com/8129237/235367951-9d459b90-ebe3-40ae-bc3d-65e3bb28a4b7.png)

- Added `if(event.cancelable)` condition to `event.preventDefault()` in `onMouseMove(event)`
![image](https://user-images.githubusercontent.com/8129237/235368295-48c0e9fd-d8bf-4886-86cf-f6d7306e4579.png)

> **Warning**
> At that point it was only possible to move the Draggable horizontally. Here starts the ugly part:

- In the Container, in addition to listening to the events, I needed to set their functions via prop:
![image](https://user-images.githubusercontent.com/8129237/235368545-42f2fe27-e7f5-42f5-a381-45978c08522b.png)

- Finally, I created a function that interrupts the scroll and checks if the clientY of the mousemove and touchmove is a value close to the edges to move the scroll via window.scrollBy(0, +-100) in onDragStart and reverts this status in onDrop. 
![image](https://user-images.githubusercontent.com/8129237/235368749-4c851c93-7b45-4321-b415-1d6428a7b89e.png)

I hope this solution helps to write a prettier solution.

**Comment by LucasRosas** [comment]
> --- en --- (pt-BR mais abaixo) I found a solution!! Not the most elegant, but it worked. 😄
> 
> * I replaced the `render` functions with `setup` and had to **import { h } from 'vue'**:
>
>  ...

wait! I just found out that this package here already has these fixes. https://www.npmjs.com/package/vue-dndrop-3

I tested it here and this bug does not exist in this version. Are there any fixes/improvements in the main package that are not in this vue-dndrop3?

**Comment by LucasRosas** [comment]
Many thanks, @novikov-dv , who managed to solve the problem :
https://github.com/novikov-dv/vue3-dndrop/blob/master/dist/vue3-dndrop.esm.js

**Comment by CedroVost** [comment]
Hi, we're having the same issue on an older vue2 project, any update on when it'll be patched?

Thanks!

**Comment by Hlautameki** [comment]
I don't get it. The simple (no tags) sample works on the official page on the touch devices. But if I implement it completely the same way locally it doesn't. After one drag it stops working.

**Comment by LucasRosas** [comment]
import { Container, Draggable } from [https://github.com/novikov-dv/vue3-dndrop/blob/master/dist/vue3-dndrop.esm.js](https://github.com/novikov-dv/vue3-dndrop/blob/master/dist/vue3-dndrop.esm.js) if you use vue3. It worked for me, @Hlautameki.

**Comment by Hlautameki** [comment]
@LucasRosas Amazing. It works. Thank you very much. You've saved me a lot of time. Especially since this library was my last hope for available drag-and-drop solutions for Vue :)

**Comment by skkap** [comment]
@amendx I see the fix has already in master for half a year. Are there any plans on making the npm release?

**Comment by amendx** [comment]
@skkap https://www.npmjs.com/package/vue-dndrop updated 👍🏼
